djangoapp/chart/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'chart'
urlpatterns = [
    path('', views.index, name='getinput')
]

djangoapp/djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chart.urls'))
]

djangoapp/chart/models.py
from django.db import models

# Create your models here.

djangoapp/chart/views.py
from django.shortcuts import render
from django import forms
from .utils import probability_prediction as pp


class NewTaskform(forms.Form):  # form for getting data needed for prediction
    gold_diff = forms.IntegerField(label='Gold difference')
    exp_diff = forms.IntegerField(label='Exp difference')
    team = forms.ChoiceField(label='team', choices=
    (
        ("red", "red"),
        ("blue", "blue"),
    )
                             )


def index(request):
    if request.method == "POST":
        form = NewTaskform(request.POST)
        if form.is_valid():
            df = pp.predict_probability_of_winning(form.cleaned_data["gold_diff"],
                                                   form.cleaned_data["exp_diff"], form.cleaned_data["team"])
            probability = round(float(df[f'{form.cleaned_data["team"]}Win']) * 100, ndigits=2)
            return render(request, 'chart/chart.html',
                          dict(probability=probability))
    else:
        return render(request, 'chart/getinput.html', {'form': NewTaskform()})

# inputing logic into html : {% if something %}
#                               some html
#                               {% else %}
#                               some html
#                              {% end if %}

djangoapp/chart/templates/chart/chart.html
{% extends "chart/layout.html"%}
{% block body%}
<h2>Look at this chart men</h2>
<!-- Resources -->
<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
<!-- todo: store gauge as distinct js file -->
<!-- Chart code -->
<script>
am4core.ready(function() {

// Themes begin
am4core.useTheme(am4themes_animated);
// Themes end

// create chart
var chart = am4core.create("chartdiv", am4charts.GaugeChart);
chart.innerRadius = am4core.percent(82);

/**
 * Normal axis
 */

var axis = chart.xAxes.push(new am4charts.ValueAxis());
axis.min = 0;
axis.max = 100;
axis.strictMinMax = true;
axis.renderer.radius = am4core.percent(80);
axis.renderer.inside = true;
axis.renderer.line.strokeOpacity = 1;
axis.renderer.ticks.template.disabled = false
axis.renderer.ticks.template.strokeOpacity = 1;
axis.renderer.ticks.template.length = 10;
axis.renderer.grid.template.disabled = true;
axis.renderer.labels.template.radius = 40;
axis.renderer.labels.template.adapter.add("text", function(text) {
  return text + "%";
})

/**
 * Axis for ranges
 */

var colorSet = new am4core.ColorSet();

var axis2 = chart.xAxes.push(new am4charts.ValueAxis());
axis2.min = 0;
axis2.max = 100;
axis2.strictMinMax = true;
axis2.renderer.labels.template.disabled = true;
axis2.renderer.ticks.template.disabled = true;
axis2.renderer.grid.template.disabled = true;

var range0 = axis2.axisRanges.create();
range0.value = 0;
range0.endValue = 50;
range0.axisFill.fillOpacity = 1;
range0.axisFill.fill = colorSet.getIndex(0);

var range1 = axis2.axisRanges.create();
range1.value = 50;
range1.endValue = 100;
range1.axisFill.fillOpacity = 1;
range1.axisFill.fill = colorSet.getIndex(2);

/**
 * Label
 */

var label = chart.radarContainer.createChild(am4core.Label);
label.isMeasured = false;
label.fontSize = 45;
label.x = am4core.percent(50);
label.y = am4core.percent(100);
label.horizontalCenter = "middle";
label.verticalCenter = "bottom";
label.text = "50%";


/**
 * Hand
 */

var hand = chart.hands.push(new am4charts.ClockHand());
hand.axis = axis2;
hand.innerRadius = am4core.percent(20);
hand.startWidth = 10;
hand.pin.disabled = true;
hand.value = 0;

hand.events.on("propertychanged", function(ev) {
  range0.endValue = ev.target.value;
  range1.value = ev.target.value;
  label.text = axis2.positionToValue(hand.currentPosition).toFixed(1);
  axis2.invalidate();
});

setInterval(function() {
  var value =  {{probability}}  //Math.round(Math.random() * 100);
  var animation = new am4core.Animation(hand, {
    property: "value",
    to: value
  }, 1000, am4core.ease.cubicOut).start();
}, 2000);

}); // end am4core.ready()
</script>

<!-- HTML -->
<div id="chartdiv"></div>
<a href="{% url 'chart:getinput' %}">go to get input</a>
{% endblock%}

djangoapp/chart/templates/chart/getinput.html
{% extends "chart/layout.html"%}
{% block body%}
<form action="{% url 'chart:getinput' %}" method="post">
    {{ form }}
    {% csrf_token %}
    <input type="submit">
</form>
{% endblock%}

djangoapp/chart/templates/chart/layout.html
{% load static %}
<!DOCTYPE html>
<!-- todo: create a prettier layout -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'chart/styles.css' %}" rel="stylesheet">
</head>
<body>
{% block body%}
{% endblock%}
</body>
</html>